### ISSUE TITLE
När inga applikationer finns registrerade

### ISSUE THREAD

**Issue by ch222kv** [HenrikGabrielsson/1DV450_hg222aa#10]
Så kan det kanske vara logiskt att visa för administratören att sådant är fallet. Alltså att istället för ett table så kan man visa en text att inga applikationer finns.

**Comment by HenrikGabrielsson** [comment]
Ganska enkel fix. nu visas ett meddelande om att antal nycklar = 0. Tack för tipset!

**Comment by 1dv450** [comment]
:+1:
