### ISSUE TITLE
Installationsbeskrivning

### ISSUE THREAD

**Issue by ib222dp** [HenrikGabrielsson/1DV450_hg222aa#15]
I stort sett är installationsbeskrivningen tydlig och utförlig, och Postman-filen hade bra tester och var bra kommenterad. 

Några saker du kan lägga till i installationsbeskrivningen:

Version av Rails och version av Ruby

Jag lade även till config.baseurl = "http://localhost:3000" i  config/environments/test.rb

"Kör bundle install" som punkt nr 3. Du skulle också kunna lägga till vilka Gems du har lagt till i Gemfile.

Slarvfel i punkt 3 och 4: kommandot är "RAKE db:migrate" och "RAKE db:seed"

Jag fick köra "rails server -b, --binding=0.0.0.0" för att kunna testköra i Nitrous och Postman (det fungerar alltså inte med bara "rails server"

Länken till mapApi:ets Readme-fil från Readme-filen på första sidan fungerar inte (får en 404-sida)

**Comment by HenrikGabrielsson** [comment]
Slarvade lite med README-filen. Fixat nu. Tack!

**Comment by 1dv450** [comment]
:+1:
