### ISSUE TITLE
Övrigt

### ISSUE THREAD

**Issue by ib222dp** [HenrikGabrielsson/1DV450_hg222aa#17]
1. På de ställen du använder limit och offset skulle du kunna använda limit och offset direkt i stället för att först hämta ut alla poster från databasen (t.ex.  creators =  Creator.limit(@limit).offset(@offset) i stället för creators = Creator.all). Om man har en stor databas är det ju onödigt att hämta ut alla poster när man ändå inte kommer att returnera allihop.
2. Jag vet inte hur det är med SQL-injections och liknande i Ruby on Rails, men i search-metoden i memories_controller är det kanske säkrare att först skriva "TERM=params[:term]", och sedan  "memories = Memory.where("title LIKE ?", "%"+TERM+"%")".
3. Jag vet egentligen inte om det är nödvändigt, men du skulle kunna ha "if memory.destroy...else bad request" som du har i create och update i memories_controller.
4. För att undvika förvirring kanske det skulle vara lämpligare att ett tag-objekt har en egenskap "name" i stället för en egenskap "tag".
5. Man behöver inte logga in för att skapa en creator. Jag antar att det är för att man inte kan logga in innan man har ett konto, vilket man får när man skapar en creator, men om man ser creator som en resurs som en User av Api:et skapar, så borde usern vara inloggad eftersom post är en "unsafe method". Men det beror väl lite på hur du designar alltihop i sin helhet, mest bara något att ha i åtanke...

**Comment by HenrikGabrielsson** [comment]
1. Detta var ett mycket bra tips, som jag inte alls tänkte på. Men nu är det ordnat. Tack så mycket! :)
2. Jag är osäker på om detta är ett problem, då jag tror att rails kommer att lösa detta åt mig. (Kolla här: http://guides.rubyonrails.org/security.html#sql-injection, under 7.2.4: Countermeasures). Jag lade till ditt förslag för att känna mig lite säkrare dock.
3. Jag lade till ett felmeddelande ifall det inte gick att ta bort minnet. Alltid bra att vara tydlig :)
4. Ja, det har blivit väldigt förvirrande även under byggandet, och jag hade nog valt att döpa om egenskapen tag till namn eller nåt liknande om jag hade gjort det igen. Kanske ändrar detta senare, men låter det vara för tillfället.
5. Precis som du säger så blir det svårt för en creator att vara inloggad när han/hon skapar sitt användarkonto :). Tänkte dock att eftersom man inte kan skapa någon annan resurs i API:et innan man har loggat in, så borde det inte vara någon större fara.

Många bra tips, tack för det!
