### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ib222dp** [HenrikGabrielsson/1DV450_hg222aa#18]
Jag tycker att applikationen i sin helhet är bra och uppfyller kraven, och koden är bra skriven och bra kommenterad. API:et följer REST och har bra felmeddelanden, statuskoder och url:er. Jag kommer nog också att låna lite från din applikation för att fixa till lite saker i min egen applikation:)

**Comment by HenrikGabrielsson** [comment]
Tackar. Gör det :)
