### ISSUE TITLE
Går att logga in på nyligen utloggad användare genom att anropa url från användares inloggning

### ISSUE THREAD

**Issue by hg222dt** [HenrikGabrielsson/1DV450_hg222aa#2]
Jag antar att du kanske redan vet detta, eftersom att du ju trots allt ändå skyddat api-nyckeln mot att hämtas, även om någon loggar in på användare genom att posta url och kunna logga in på dennes konto. Det kändes bara lite märkligt att en inloggning på utloggad användare trots allt överhuvudtaget går att göra. Vore det inte bättre att göra din check på inloggad-användare i application_controller för att alltid se om en användare är behörig att utföra en operation, istället för att bra gör en sådan check i keys_controller? Eller åtminstone så att all användar-hantering kollas av när någon ska logga in.

**Comment by HenrikGabrielsson** [comment]
Pinsamt att jag missade detta. Tanken är att man inte ska kunna se /users/{id} utan att vara inloggad som just den användaren. har fixat det nu, men tack för att du pekade ut det :)

**Comment by 1dv450** [comment]
:+1:
