### ISSUE TITLE
Nycklar kan tas bort av administratören utan confirmation

### ISSUE THREAD

**Issue by ch222kv** [HenrikGabrielsson/1DV450_hg222aa#8]
När man har loggat in som administratör så får man upp en lista över api nycklar, med en ta bort länk. Om man klickar på länken så tas applikationen omedelbart bort utan någon confirmation. Det blir lite jobbigt för en användare om administratören skulle råka göra så på en riktig nyckel.

**Comment by HenrikGabrielsson** [comment]
Kan hålla med om att det känns lite farligt i keys-listan utan någon confirmation. Jag lade till detta i rails vilket tyvärr visar sig som en alert-ruta, men det är bättre än inget.
